### ISSUE TITLE
Double proxies?

### ISSUE THREAD

**Issue by bradezard131** [defeo/jupyterhub-docker#10]
It appears that you use two proxies in this configuration. The Traefik proxy, which is set up to run in an external container to the hub; and the normal inbuilt configurable-http-proxy which runs inside the JupyterHub container and manages all the internal routing. Is this by design? it seems strange to me to have both proxies in the same system

**Comment by defeo** [comment]
They play two different roles. If you want to use Traefik for both, see https://discourse.jupyter.org/t/introducing-traefikproxy-a-scalable-and-highly-available-proxy-for-jupyterhub/445
