### ISSUE TITLE
It seems jupyter-config.py has no effect

### ISSUE THREAD

**Issue by Adrast** [defeo/jupyterhub-docker#8]
I've tried to setup a basic example, but no matter how I configure jupyter-config.py regarding Auth, it keeps defaulting to PAM. Even when I use the default CAS auth.

**Comment by defeo** [comment]
Have you paid attention to this sentence [here](https://opendreamkit.org/2018/10/17/jupyterhub-docker/#data-persistence):

> Be careful with this configuration: if you update jupyterhub_config.py and rebuild the jupyterhub service, the contents will not be updated inside the volume, unless you destroy it first with docker volume rm.
